portfolio/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

    resources :photos
    resources :tags

end

portfolio/app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader
  has_many :phototags
  has_many :tags, through: :phototags

end

portfolio/app/models/phototag.rb
class Phototag < ActiveRecord::Base
  belongs_to :photo
  belongs_to :tag
end

portfolio/app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :phototags
  has_many :photos, through: :phototags

end

portfolio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

portfolio/app/controllers/concerns/tags_to_show_concern.rb
module TagsToShowConcern
  extend ActiveSupport::Concern

  included do
    helper_method :tags_to_show
  end

  def tags_to_show
    @photos = Photo.all
    # copied into tags_controller as well
    tags = Tag.all
    # hardcoding allowed tags for now until they fill up
    # remove from here down and update tags=Tag.all to @tags=Tag.all
    tags_to_show = ["dogs", "sweet", "savory", "portrait", "scenery", "foodstyling"]
    @tags = []
    tags.each do |tag|
      if tags_to_show.include?(tag.name)
        @tags << tag
      end 
    end
    return @tags
  end

end

portfolio/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include TagsToShowConcern

  def new
    tags = Tag.all
    @tags = ""
    tags.each do |tag|
      @tags = @tags + "##{tag.name} "
    end
    puts "TAGS: #{@tags}"
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def index
    @photos = Photo.all
    @photos = @photos.reverse
    @photos.each do |x|
      puts "#{x.title}"
    end
    @tags = tags_to_show
  end

  def create
    # create an array of tags
    tags = params["photo"]["tags"]
    # tags should be in the format: #yolo #puppies
    tags = tags.split("#")
    stripped_tags = []
    tags.each do |tag|
      tag = tag.strip
      if tag.length > 0
        stripped_tags << tag
      end
    end
    params["photo"].delete :tags

    # create a photo
    puts "going to run photo.new"
    @photo = Photo.new(article_params)
    @photo.save
    puts @photo.errors.messages.inspect
    puts "Photo: #{@photo}"
    
    # if tags, populate tags
    stripped_tags.each do |tag|
      @tag = Tag.find_by_name(tag)
      if !@tag
        @tag = Tag.new({:name => tag})
        @tag.save
      end
      @tag.phototags.create(photo: @photo)
    end

    redirect_to @photo

  end

  private
  def article_params
    params.require(:photo).permit(:title, :description, :image)
  end

end

portfolio/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include TagsToShowConcern

  def index
    @tags = tags_to_show
  end

  def show
    @tags = tags_to_show
    @tag = Tag.find(params[:id])
    photos = Photo.all
    @photos = []
    photos.each do |photo|
      if photo.tags.include?(@tag)
        @photos << photo
      end
    end
    @photos = @photos.reverse
  end

end

portfolio/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio/app/helpers/photos_helper.rb
module PhotosHelper
end

portfolio/app/helpers/tags_helper.rb
module TagsHelper
end

portfolio/app/helpers/welcome_helper.rb
module WelcomeHelper
end

portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

portfolio/app/views/photos/index.html.erb
<%= render :partial => "shared/tagsheader" %>
<%= render :partial => "shared/layout" %>

portfolio/app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= form_for :photo, url: photos_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :tags %><br>
    <%= f.text_area(:tags, :placeholder => @tags) %>
  </p>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

portfolio/app/views/photos/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @photo.image.large.url %>
</p>

portfolio/app/views/shared/_layout.html.erb
<div id="main-container" class="container">
  <div class="row">

    <div class="col-xs-1 sidebar">
    </div>

    <div id="content" class="col-xs-10 content">
        <% @photos.each do |photo| %>
              <div class="feed-photo-container">
                <%= link_to photo_path(photo) do %>
                  <%= image_tag photo.image.medium.url, class: "feed-photo" %>
                <% end %>
              </div>
            <% end %>
    </div>

    <div class="col-xs-1 sidebar">
    </div>

  </div>
</div>


<script type="text/javascript">
    $('body').ready(function() { 

        $('img').hide();
        $('img').each(function(i) {
            if (this.complete) {
                $(this).fadeIn(1000);
            } else {
                $(this).load(function() {
                    $(this).fadeIn(1000);
                });
            }
        });
    });
</script>

portfolio/app/views/shared/_tagsheader.html.erb
<div id="ruinakata">
  <p>R U I    N A K A T A</p>
</div>

<div class="tags-container container">
  <div class="row">
<!--     <div class="col-xs-3 sidebar">
    </div> -->

    <% @tags.each do |tag| %>
      <div class="tag-container col-md-2">
        <%= link_to "#{tag.name}", tag_path(tag), class: "tag" %>
      </div>
    <% end %>

<!--     <div class="col-xs-3 sidebar">
    </div> -->

  </div>
</div>

portfolio/app/views/tags/index.html.erb
<%= render :partial => "shared/tagsheader" %>

portfolio/app/views/tags/show.html.erb
<%= render :partial => "shared/tagsheader" %>
<%= render :partial => "shared/layout" %>

portfolio/app/views/welcome/index.html.erb
<p>WELCOME TO MY PORTFOLIO</p>

Tags: <>

Show all here